#ifndef LISTCOMPARISON_GLOBAL_H
#define LISTCOMPARISON_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LISTCOMPARISON_LIBRARY)
#  define LISTCOMPARISON_EXPORT Q_DECL_EXPORT
#else
#  define LISTCOMPARISON_EXPORT Q_DECL_IMPORT
#endif

#endif // LISTCOMPARISON_GLOBAL_H
